### ISSUE TITLE
code { margin: 0 2px } in site.css breaks the alignment of the 1st line in pre > code 

### ISSUE THREAD

**Issue by Crystal-RainSlide** [codemirror/website#4]
The code:

``` CSS
code { margin: 0 2px }
```

in:

https://github.com/codemirror/website/blob/master/site/style/site.css#L285

will also give a `2px` margin to the start or the first and the end of the last line of `pre > code`s, or the code blocks.

----

Another line of the code:

``` CSS
pre > code { margin: 0 }
```

will fix it, but I suggest to remove the margin, as it is not very essensial, `<code>` won't kill the width of the blank characters.
